# We create a PVC only if the default PVC name has not changed.
# If the name has changed, it means our users want to use their own pre-provisioned PVC.
# In such cases it would be an error to create a PVC as it would result in a conflict - the PVC already exists.
{{- if .Values.pvc.enabled }}{{- if eq .Values.pvc.name "snyk-monitor-pvc" }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.pvc.name }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.temporaryStorageSize }}
  {{- if .Values.pvc.storageClassName }}
  {{- if (eq "-" .Values.pvc.storageClassName) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.pvc.storageClassName }}"
  {{- end }}
  {{- end }}
{{- end }}{{- end }}
